kind: Pod
apiVersion: v1
metadata:
  name: hayhooks
  labels:
    app: haystack
spec:
  containers:
  - image: deepset/hayhooks:main
    name: hayhooks
    imagePullPolicy: Always
    # Mount the ConfigMap at /opt/pipelines inside the container.
    volumeMounts:
      - name: config-volume
        mountPath: /opt/pipelines
    # Tell Hayhooks where to find the pipeline definitions.
    env:
      - name: HAYHOOKS_PIPELINES_DIR
        value: /opt/pipelines
  volumes:
    - name: config-volume
      configMap:
        name: pipelines
