apiVersion: v1
kind: Service
metadata:
  name: haystack-service
spec:
  selector:
    app: haystack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  # Falls du externen Zugriff willst, später auf "LoadBalancer" oder "NodePort" ändern
