apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: haystack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686
            - containerPort: 14268
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: haystack-app
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
      name: ui
    - protocol: TCP
      port: 14268
      targetPort: 14268
      name: collector
  type: ClusterIP
