apiVersion: v1
kind: Secret
metadata:
  name: haystack-secrets
  namespace: haystack-app
type: Opaque
data:
  OPENAI_API_KEY: "c2stcHJvai1WcWtiWjI1VThoRGhfUmhXSzlkdXpIV2xCbG1fY282cV96eDI5M2NMdDhBOE9FMGo3MGwyc2p6bldPZ0JSbjBfSFVDRG42eDlfeVQzQmxia0ZKMk1LdTYtSU9pN1hpQ1BoOEkzczRuWjljUlhpVEdVekRqT3FQZ2ROQXlnMXNjWklvYUl3b0NFR3N4STlIdVhka21KYVJUX2Z6b0E="
  WEAVIATE_API_KEY: "YzNhbENnSnR0VUR5YzBsdGNONDVHWnl0bk9wQnpJaE1Eb21F"
